name: Java CI

on: [push, pull_request]

jobs:
  build:

    strategy:
      fail-fast: false    # run all parallel jobs
      matrix:
        gradle:
          - 6.0.1         # latest version
          - 5.6.4
          - 5.5.1
          - 5.4.1
          - 5.3.1
          - 5.2.1
          - 5.1.1
          - 4.10.3
          - 4.9
          - 4.8.1
          - 4.7           # current version

    runs-on: ubuntu-latest

    env:
      GRADLE_OPTS: "-Xmx6g -Xms4g"

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: check
          gradle-version: ${{ matrix.gradle }}